import pickle
import numpy as np
import os
from music21 import instrument, note, stream, chord
from keras.models import load_model

def generate_notes(model, network_input, pitches, n_vocab, num_notes=200, temperature=1.0):
    """
    Generate notes from the neural network based on a sequence of notes.
    
    Args:
        model: Trained Keras model
        network_input: Input sequences from training
        pitches: List of unique pitches
        n_vocab: Size of vocabulary
        num_notes (int): Number of notes to generate
        temperature (float): Sampling temperature (higher = more random)
        
    Returns:
        list: Generated note predictions
    """
    # Pick a random sequence from the input as a starting point
    start = np.random.randint(0, len(network_input) - 1)
    
    int_to_note = dict((number, note) for number, note in enumerate(pitches))
    
    # Use a copy of the input pattern to generate the sequence
    pattern = network_input[start].flatten().tolist()
    # Ensure they are integers since the normalized values were divided by n_vocab
    pattern = [int(p * n_vocab) for p in pattern]
    
    prediction_output = []
    
    print(f"Generating {num_notes} notes...")
    
    # Generate notes
    for note_index in range(num_notes):
        # Reshape and normalize the pattern matching the trained sequence format
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))
        prediction_input = prediction_input / float(n_vocab)
        
        prediction = model.predict(prediction_input, verbose=0)
        
        # Apply temperature to prediction
        prediction = np.log(prediction + 1e-10) / temperature
        exp_preds = np.exp(prediction)
        prediction = exp_preds / np.sum(exp_preds)
        
        # Sample from the prediction distribution
        index = np.random.choice(len(prediction[0]), p=prediction[0])
        
        result = int_to_note[index]
        prediction_output.append(result)
        
        pattern.append(index)
        pattern = pattern[1:len(pattern)]
        
        if (note_index + 1) % 50 == 0:
            print(f"  Generated {note_index + 1}/{num_notes} notes")
    
    print(f"Generation complete!")
    return prediction_output

def create_midi(prediction_output, filename='output.mid'):
    """
    Convert the output from the prediction to notes and create a midi file.
    
    Args:
        prediction_output (list): List of predicted notes/chords
        filename (str): Output MIDI filename
    """
    offset = 0
    output_notes = []
    
    print(f"\nConverting {len(prediction_output)} predictions to MIDI...")
    
    # Create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # Pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                try:
                    new_note = note.Note(int(current_note))
                    new_note.storedInstrument = instrument.Piano()
                    notes.append(new_note)
                except:
                    # Skip invalid notes
                    continue
            
            if notes:
                new_chord = chord.Chord(notes)
                new_chord.offset = offset
                output_notes.append(new_chord)
        # Pattern is a note
        else:
            try:
                new_note = note.Note(pattern)
                new_note.offset = offset
                new_note.storedInstrument = instrument.Piano()
                output_notes.append(new_note)
            except:
                # Skip invalid notes
                continue
            
        # Increase offset each iteration so that notes do not stack
        offset += 0.5
    
    if not output_notes:
        raise ValueError("No valid notes generated. Cannot create MIDI file.")
    
    midi_stream = stream.Stream(output_notes)
    
    # Ensure output directory exists
    output_dir = os.path.dirname(filename)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    midi_stream.write('midi', fp=filename)
    print(f"Generated MIDI saved as: {filename}")

if __name__ == "__main__":
    print("=" * 60)
    print("MUSIC AI - MUSIC GENERATION")
    print("=" * 60)
    
    # Check if required files exist
    if not os.path.exists('model.keras'):
        raise FileNotFoundError(
            "model.keras not found. Please train the model first using train.py"
        )
    
    if not os.path.exists('notes.pkl'):
        raise FileNotFoundError(
            "notes.pkl not found. Please run preprocess.py first"
        )
    
    if not os.path.exists('network_data.pkl'):
        raise FileNotFoundError(
            "network_data.pkl not found. Please run preprocess.py first"
        )
    
    # Load vocabulary and input data
    print("\nLoading data...")
    with open('notes.pkl', 'rb') as filepath:
        notes = pickle.load(filepath)
    with open('network_data.pkl', 'rb') as filepath:
        data = pickle.load(filepath)
        
    network_input = data['input']
    
    pitches = sorted(set(item for item in notes))
    n_vocab = len(set(notes))
    
    print(f"Vocabulary size: {n_vocab}")
    
    # Load model
    print("\nLoading trained model...")
    model = load_model('model.keras')
    
    # Generate notes
    print("\nGenerating music...")
    prediction_output = generate_notes(
        model, 
        network_input, 
        pitches, 
        n_vocab,
        num_notes=200,  # Generate 200 notes
        temperature=1.0  # Adjust for more/less randomness (0.5-1.5)
    )
    
    # Create MIDI file
    output_filename = 'generated_data/aether_track.mid'
    create_midi(prediction_output, filename=output_filename)
    
    print("\n" + "=" * 60)
    print("Music generation complete!")
    print(f"Output saved to: {output_filename}")
    print("=" * 60)
