import React, { useState, useEffect } from 'react'
import { 
    Compass, Play, Heart, Share2, 
    Search, Filter, Headphones, Music,
    Zap, Sparkles, TrendingUp, Clock, Loader2,
    User, MoreHorizontal, Layers, ChevronRight
} from 'lucide-react'

export function DiscoverPage() {
    const [tracks, setTracks] = useState([])
    const [loading, setLoading] = useState(true)
    const [activeGenre, setActiveGenre] = useState('All')
    const [searchQuery, setSearchQuery] = useState('')
    const [hoveredTrack, setHoveredTrack] = useState(null)

    const genres = ['All', 'Synthwave', 'Cinematic', 'Lo-Fi', 'Techno', 'Ambient', 'Drum & Bass']

    useEffect(() => {
        const fetchTracks = async () => {
            try {
                const response = await fetch('http://127.0.0.1:8000/api/discover')
                const data = await response.json()
                if (data.success) {
                    setTracks(data.tracks)
                }
            } catch (error) {
                console.error("Failed to fetch discover feed:", error)
            } finally {
                setLoading(false)
            }
        }
        fetchTracks()
    }, [])

    const filteredTracks = tracks.filter(track => {
        const matchesGenre = activeGenre === 'All' || track.genre === activeGenre
        const matchesSearch = track.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                             track.artist.toLowerCase().includes(searchQuery.toLowerCase())
        return matchesGenre && matchesSearch
    })

    const featuredTrack = tracks[0] || null

    return (
        <div className="discover-root animate-fade-in">
            {/* Header / Search Area */}
            <header className="discover-header">
                <div className="header-text">
                    <h1 className="header-title">
                        <div className="icon-badge">
                            <Compass size={24} />
                        </div>
                        Neural Network
                    </h1>
                    <p className="header-desc">
                        Explore the high-fidelity masterpieces generated by the Aether community.
                    </p>
                </div>

                <div className="header-actions">
                    <div className="search-bar-container">
                        <Search size={18} className="search-icon" />
                        <input 
                            type="text" 
                            placeholder="Search the Matrix..." 
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="discover-search-input"
                        />
                    </div>
                    <div className="user-profile-header">
                         <div className="user-profile-summary">
                            <div className="user-avatar-small">
                                <User size={14} />
                            </div>
                            <div className="user-meta">
                                <span className="email-truncated">user@example.com</span>
                                <span className="badge-free">Free</span>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            {/* Featured Hero Section */}
            {!loading && featuredTrack && activeGenre === 'All' && !searchQuery && (
                <section className="featured-hero">
                    <div className="featured-content">
                        <div className="featured-label"><TrendingUp size={14} /> Trending Now</div>
                        <h2 className="featured-title">{featuredTrack.title}</h2>
                        <div className="featured-meta">
                            <span className="featured-artist">by {featuredTrack.artist}</span>
                            <span className="dot">•</span>
                            <span className="featured-genre">{featuredTrack.genre}</span>
                        </div>
                        <p className="featured-blurb">
                            An ethereal journey through digital landscapes, masterfully synthesized 
                            using the latest Aether-V3 neural logic.
                        </p>
                        <div className="featured-btns">
                            <button className="aether-btn-primary play-btn-large">
                                <Play size={20} fill="currentColor" /> Play Masterpiece
                            </button>
                            <button className="aether-btn-outline fork-btn-large">
                                <Layers size={18} /> Fork Track
                            </button>
                        </div>
                    </div>
                    <div className="featured-visual">
                         <div className="visual-orb" style={{ background: `radial-gradient(circle, ${featuredTrack?.color || 'var(--aether-cyan)'} 0%, transparent 70%)` }}></div>
                         <div className="waveform-animation">
                            {[...Array(30)].map((_, i) => (
                                <div key={i} className="wf-bar" style={{ animationDelay: `${i * 0.05}s` }}></div>
                            ))}
                         </div>
                    </div>
                </section>
            )}

            {/* Genre Filter Bar */}
            <nav className="genre-bar">
                {genres.map(genre => (
                    <button 
                        key={genre}
                        className={`genre-pill ${activeGenre === genre ? 'active' : ''}`}
                        onClick={() => setActiveGenre(genre)}
                    >
                        {genre}
                    </button>
                ))}
            </nav>

            {/* Track Grid */}
            <div className="track-grid-container">
                {loading ? (
                    <div className="loading-state">
                        <Loader2 size={48} className="animate-spin text-cyan" />
                        <p>Loading Neural Feed...</p>
                    </div>
                ) : filteredTracks.length > 0 ? (
                    <div className="discover-grid">
                        {filteredTracks.map(track => (
                            <div 
                                key={track.id} 
                                className="track-card"
                                onMouseEnter={() => setHoveredTrack(track.id)}
                                onMouseLeave={() => setHoveredTrack(null)}
                            >
                                <div className="card-artwork">
                                    <div className="artwork-overlay">
                                        <button className="play-overlay-btn">
                                            <Play size={24} fill="white" />
                                        </button>
                                    </div>
                                    <div className="artwork-glow" style={{ background: track.color }}></div>
                                    <Music className="artwork-placeholder-icon" size={40} />
                                    {/* Genre Tag */}
                                    <div className="track-genre-tag" style={{ color: track.color }}>{track.genre}</div>
                                </div>
                                <div className="card-info">
                                    <div className="track-row">
                                        <h3 className="track-card-title">{track.title}</h3>
                                        <span className="track-duration">{track.duration}</span>
                                    </div>
                                    <p className="track-card-artist">{track.artist}</p>
                                    <div className="track-footer">
                                        <div className="track-stats">
                                            <span><Headphones size={12} /> {track.plays}</span>
                                            <span><Heart size={12} /> {track.likes}</span>
                                        </div>
                                        <div className="track-actions">
                                            <button className="action-btn"><Share2 size={14} /></button>
                                            <button className="action-btn"><MoreHorizontal size={14} /></button>
                                        </div>
                                    </div>
                                </div>
                                {hoveredTrack === track.id && (
                                    <div className="track-hover-details animate-slide-up">
                                        <div className="tags">
                                            {track.tags.map(tag => (
                                                <span key={tag} className="tag-pill">#{tag}</span>
                                            ))}
                                        </div>
                                        <button className="aether-btn-primary fork-mini-btn">
                                            <Layers size={14} /> Fork
                                        </button>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="empty-state">
                        <Sparkles size={48} className="text-muted" />
                        <h3>No Tracks Found</h3>
                        <p>Try adjusting your neural search or filters.</p>
                    </div>
                )}
            </div>

            <style>{`
                .discover-root {
                    width: 100%;
                    max-width: 1400px;
                    margin: 0 auto;
                    padding: 1rem 1.5rem;
                    display: flex;
                    flex-direction: column;
                    gap: 2rem;
                }

                .discover-header {
                    display: flex;
                    justify-content: space-between;
                    align-items: flex-start;
                }

                .icon-badge {
                    width: 44px;
                    height: 44px;
                    background: rgba(0, 255, 204, 0.1);
                    border: 1px solid rgba(0, 255, 204, 0.2);
                    border-radius: var(--rounded-md);
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    color: var(--aether-cyan);
                    margin-bottom: 1rem;
                }

                .header-title {
                    font-size: 1.75rem;
                    font-weight: 900;
                    letter-spacing: -0.05em;
                    display: flex;
                    align-items: center;
                    gap: 0.75rem;
                }

                .header-desc {
                    color: var(--aether-text-muted);
                    font-size: 1.125rem;
                    margin-top: 0.5rem;
                }

                .header-actions {
                    display: flex;
                    align-items: center;
                    gap: 1.5rem;
                }

                .search-bar-container {
                    position: relative;
                    width: 300px;
                }

                .discover-search-input {
                    width: 100%;
                    background: var(--aether-glass);
                    border: 1px solid var(--aether-border);
                    border-radius: var(--rounded-full);
                    padding: 0.75rem 1rem 0.75rem 2.75rem;
                    color: white;
                    font-size: 0.875rem;
                    outline: none;
                    transition: all 0.3s;
                }

                .discover-search-input:focus {
                    border-color: var(--aether-cyan);
                    box-shadow: 0 0 15px rgba(0, 255, 204, 0.2);
                }

                .search-icon {
                    position: absolute;
                    left: 1rem;
                    top: 50%;
                    transform: translateY(-50%);
                    color: var(--aether-text-muted);
                }

                /* Featured Hero Section */
                .featured-hero {
                    background: var(--aether-glass);
                    border-radius: var(--rounded-lg);
                    border: 1px solid var(--aether-border);
                    padding: 2rem;
                    display: grid;
                    grid-template-columns: 1fr 1fr;
                    gap: 2rem;
                    overflow: hidden;
                    position: relative;
                    min-height: 320px;
                    align-items: center;
                }

                .featured-hero::after {
                    content: '';
                    position: absolute;
                    top: 0; right: 0;
                    width: 40%; height: 100%;
                    background: linear-gradient(to left, rgba(0, 255, 204, 0.05), transparent);
                    pointer-events: none;
                }

                .featured-label {
                    display: inline-flex;
                    align-items: center;
                    gap: 0.5rem;
                    background: rgba(0, 255, 204, 0.1);
                    color: var(--aether-cyan);
                    font-size: 0.75rem;
                    font-weight: 900;
                    text-transform: uppercase;
                    padding: 0.45rem 0.75rem;
                    border-radius: var(--rounded-sm);
                    margin-bottom: 1.5rem;
                }

                .featured-title {
                    font-size: 3.5rem;
                    font-weight: 950;
                    line-height: 1.1;
                    margin-bottom: 1rem;
                    letter-spacing: -0.04em;
                    background: linear-gradient(to right, #fff, var(--aether-text-muted));
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                }

                .featured-meta {
                    display: flex;
                    align-items: center;
                    gap: 0.75rem;
                    margin-bottom: 1.5rem;
                }

                .featured-artist { font-weight: 700; color: white; }
                .featured-genre { color: var(--aether-cyan); font-weight: 800; text-transform: uppercase; font-size: 0.75rem; letter-spacing: 0.05em; }
                .dot { color: var(--aether-text-muted); }

                .featured-blurb {
                    color: var(--aether-text-muted);
                    font-size: 1.125rem;
                    line-height: 1.6;
                    max-width: 500px;
                    margin-bottom: 2.5rem;
                }

                .featured-btns { display: flex; gap: 1rem; }
                .play-btn-large { padding: 1rem 2.5rem; font-size: 1.125rem; font-weight: 900; }
                .fork-btn-large { padding: 1rem 2rem; font-size: 1rem; font-weight: 800; border-radius: var(--rounded-md); }

                .featured-visual {
                    position: relative;
                    height: 100%;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }

                .visual-orb {
                    position: absolute;
                    width: 300px;
                    height: 300px;
                    border-radius: 50%;
                    filter: blur(40px);
                    animation: pulse-orb 4s infinite alternate;
                }

                .waveform-animation {
                    display: flex;
                    align-items: center;
                    gap: 4px;
                    height: 120px;
                    z-index: 1;
                }

                .wf-bar {
                    width: 6px;
                    border-radius: 3px;
                    background: white;
                    animation: wf-bounce 1s infinite ease-in-out;
                }

                @keyframes wf-bounce {
                    0%, 100% { height: 20px; opacity: 0.3; }
                    50% { height: 80px; opacity: 1; }
                }

                @keyframes pulse-orb {
                    from { transform: scale(1); opacity: 0.4; }
                    to { transform: scale(1.2); opacity: 0.7; }
                }

                /* Genre Bar */
                .genre-bar {
                    display: flex;
                    gap: 0.75rem;
                    overflow-x: auto;
                    padding-bottom: 0.5rem;
                    scrollbar-width: none;
                }

                .genre-pill {
                    padding: 0.65rem 1.5rem;
                    background: var(--aether-glass);
                    border: 1px solid var(--aether-border);
                    border-radius: var(--rounded-full);
                    color: var(--aether-text-muted);
                    font-size: 0.875rem;
                    font-weight: 700;
                    white-space: nowrap;
                    cursor: pointer;
                    transition: all 0.2s;
                }

                .genre-pill:hover { border-color: rgba(255,255,255,0.3); color: white; }
                .genre-pill.active { background: white; color: black; border-color: white; }

                /* Discover Grid */
                .discover-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
                    gap: 2rem;
                }

                .track-card {
                    background: var(--aether-glass);
                    border: 1px solid var(--aether-border);
                    border-radius: var(--rounded-lg);
                    padding: 1.25rem;
                    position: relative;
                    transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
                    cursor: pointer;
                }

                .track-card:hover {
                    transform: translateY(-8px);
                    border-color: rgba(255,255,255,0.4);
                    box-shadow: 0 15px 30px rgba(0,0,0,0.4);
                }

                .card-artwork {
                    width: 100%;
                    aspect-ratio: 1;
                    background: var(--aether-void);
                    border-radius: var(--rounded-md);
                    margin-bottom: 1.25rem;
                    position: relative;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    overflow: hidden;
                }

                .artwork-glow {
                    position: absolute;
                    width: 100%;
                    height: 100%;
                    opacity: 0.15;
                    filter: blur(20px);
                }

                .artwork-overlay {
                    position: absolute;
                    width: 100%;
                    height: 100%;
                    background: rgba(0,0,0,0.4);
                    backdrop-filter: blur(2px);
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    opacity: 0;
                    transition: opacity 0.3s;
                    z-index: 2;
                }

                .track-card:hover .artwork-overlay { opacity: 1; }

                .play-overlay-btn {
                    width: 64px; height: 64px;
                    border-radius: 50%;
                    background: var(--aether-cyan);
                    border: none;
                    display: flex; align-items: center; justify-content: center;
                    transform: scale(0.8);
                    transition: transform 0.2s;
                }

                .play-overlay-btn:hover { transform: scale(1); }

                .track-genre-tag {
                    position: absolute;
                    top: 1rem; right: 1rem;
                    font-size: 0.65rem; font-weight: 900;
                    text-transform: uppercase;
                    background: rgba(0,0,0,0.6);
                    padding: 0.35rem 0.6rem;
                    border-radius: var(--rounded-sm);
                    backdrop-filter: blur(4px);
                    z-index: 1;
                }

                .card-info { position: relative; }
                .track-row { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 0.25rem; }
                .track-card-title { font-size: 1.125rem; font-weight: 800; color: white; }
                .track-duration { font-size: 0.75rem; color: var(--aether-text-muted); font-family: monospace; }
                .track-card-artist { font-size: 0.875rem; color: var(--aether-text-muted); margin-bottom: 1.25rem; }

                .track-footer {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    border-top: 1px solid var(--aether-border);
                    padding-top: 1rem;
                }

                .track-stats { display: flex; gap: 1rem; font-size: 0.75rem; color: var(--aether-text-muted); }
                .track-stats span { display: flex; align-items: center; gap: 0.35rem; }

                .track-actions { display: flex; gap: 0.5rem; }
                .action-btn { 
                    width: 32px; height: 32px; 
                    background: transparent; border: none; 
                    color: var(--aether-text-muted); 
                    cursor: pointer; border-radius: 50%;
                    transition: all 0.2s;
                }
                .action-btn:hover { background: var(--aether-glass-white); color: white; }

                .track-hover-details {
                    position: absolute;
                    bottom: 0; left: 0; right: 0;
                    background: var(--aether-glass);
                    backdrop-filter: blur(12px);
                    padding: 1rem;
                    border-radius: 0 0 var(--rounded-lg) var(--rounded-lg);
                    border-top: 1px solid var(--aether-border);
                    display: flex;
                    flex-direction: column;
                    gap: 1rem;
                    z-index: 10;
                }

                .tags { display: flex; flex-wrap: wrap; gap: 0.5rem; }
                .tag-pill { font-size: 0.65rem; color: var(--aether-cyan); font-weight: 700; opacity: 0.8; }
                .fork-mini-btn { padding: 0.5rem; font-size: 0.75rem; font-weight: 900; }

                /* User Profile Mock Port */
                .user-profile-header {
                    display: flex;
                    align-items: center;
                    gap: 0.75rem;
                    background: var(--aether-glass);
                    padding: 0.35rem 1rem;
                    border-radius: var(--rounded-full);
                    border: 1px solid var(--aether-border);
                    backdrop-filter: blur(12px);
                }

                .user-profile-summary {
                    display: flex;
                    align-items: center;
                    gap: 0.65rem;
                }

                .user-avatar-small {
                    width: 24px;
                    height: 24px;
                    border-radius: 50%;
                    background: linear-gradient(135deg, var(--aether-violet), var(--aether-pink));
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    color: white;
                }

                .user-meta { display: flex; flex-direction: column; }
                .email-truncated { font-size: 0.7rem; font-weight: 700; color: white; }
                .badge-free { font-size: 0.55rem; font-weight: 800; color: var(--aether-cyan); text-transform: uppercase; }

                .loading-state, .empty-state {
                    flex: 1; display: flex; flex-direction: column; 
                    align-items: center; justify-content: center; 
                    gap: 1.5rem; min-height: 400px;
                    color: var(--aether-text-muted);
                }
                .empty-state h3 { color: white; font-weight: 800; }

                .animate-slide-up {
                    animation: slide-up 0.3s cubic-bezier(0.16, 1, 0.3, 1);
                }

                @keyframes slide-up {
                    from { transform: translateY(10px); opacity: 0; }
                    to { transform: translateY(0); opacity: 1; }
                }
            `}</style>
        </div>
    )
}
